apiVersion: v1
kind: Service
metadata:
  name: spagobi-mysql-svc1
  labels:
    name: spagobi-mysql-svc1
spec:
  type: ClusterIp
  ports:
  - port: 3306
  selector:
    app: spagobi-mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spagobi-mysql
  labels:
    app: spagobi-mysql
spec:
  serviceName: spagobi-mysqlsvc
  updateStrategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: spagobi-mysql
  template:
    metadata:
      labels:
        app: spagobi-mysql
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: spagobi-mysql
        image: mysql:5.5
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: "spagobidb"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        volumeMounts:
        - name: spagobi-mysql-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: spagobi-mysql-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 20Gi
