apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spagobi-mysql
  labels:
    app: spagobi
spec:
  serviceName: spagobi-mysql
    updateStrategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: spagobi-mysql
  template:
    metadata:
      labels:
        app: spagobi-mysql
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: spagobi
        image: mysql:5.5
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        volumeMounts:
        - name: spagobi-mysql-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: spagobi-mysql-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 20Gi
